from django.db import models
from django.utils import timezone
from events.models import Event
from django.contrib.contenttypes.models import ContentType
import logging

class Source(models.Model):
    real_type = models.ForeignKey(ContentType, editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.real_type = self._get_real_type()
        super(Source, self).save(*args, **kwargs)

    def _get_real_type(self):
        return ContentType.objects.get_for_model(type(self))

    def cast(self):
        return self.real_type.get_object_for_this_type(pk=self.pk)
    
    name = models.TextField(max_length=60)
    description = models.TextField(max_length=250)
    events = models.ManyToManyField(Event, through='EventGenerator')
    
    def _event_generated(self, ev):
        logging.info("Event %s generated by %s"%(ev.title,self.name))
        ed = EventGenerator.objects.create(disptcher=self, event=ev,
                                            when=timezone.now())
        ed.save()
        
    @classmethod
    def get_url_name(cls,tag=''):
        return cls.cls_tag + tag

    @classmethod
    def get_detail_url_name(cls):
        return cls.get_url_name('.detail')
    
    def get_obj_detail_url_name(self):
        return self.cast().get_detail_url_name()

    @classmethod
    def get_index_url_name(cls):
        return cls.get_url_name()
    
    def get_obj_index_url_name(self):
        return self.cast().get_index_url_name()
    
    def get_cls_tag(self):
        return self.cast().cls_tag

class EventGenerator(models.Model):
    event = models.ForeignKey(Event)
    source = models.ForeignKey(Source)
    when = models.DateField()

class DebugSource(Source):
    cls_tag = "dbg"
    tag = models.TextField(max_length=60)

class TestSource(Source):
    cls_tag = "tst"
    test = models.TextField(max_length=25)
